### ISSUE TITLE
docker-lock fails parsing docker-compose files when using service profiles

### ISSUE THREAD

**Issue by andoks** [safe-waters/docker-lock#105]
Version [1.28.0](https://github.com/docker/compose/releases/tag/1.28.0) of docker-compose introduced a new service profiles feature which add a new property "profiles" to services ([docker compose documentation](https://docs.docker.com/compose/profiles/)). Using this feature in compose-files makes docker-lock fail with the following error:
>  'docker-compose.yml' failed to load with err: services.prometheus Additional property profiles is not allowed

docker lock version
```
$ docker lock version     
0.8.6
```

**Comment by michaelperel** [comment]
The same comments about [docker stack](https://github.com/safe-waters/docker-lock/issues/89#issuecomment-766466562) from this issue apply. Namely, where docker stack differs from docker-compose, docker-lock will fail. In my own uses, I have not run into divergences, so I appreciate you opening an issue on this.

The reason for using the docker stack code was that docker-compose was written in python, so the closest approximation was to use the code from docker stack in go.

However, [now that docker-compose has been included in go in the docker cli](https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose), I believe I can fix small edge cases like this by relying on the go code for docker-compose.

If that does not work, I can take out the validation logic that causes this to fail, as it is not entirely necessary, but I thought it was a nice to have so that docker-lock would fail on invalid docker-compose files.

I hope to fix this next week with one of those 2 solutions.

**Comment by michaelperel** [comment]
To fix this issue quickly, I am skipping validation (as it is just a nice to have). However, I tried to use the new loader that I mentioned above, but I ran into [what I believe is a bug](https://github.com/compose-spec/compose-go/issues/148).

I will cut a new release today, and when that bug gets fixed / I get a reply, I will update to using the new loader (although this should not change docker-lock's behavior at all, given that validation is turned off).

**Comment by michaelperel** [comment]
The new release is v0.8.7, thanks for opening an issue!

**Comment by andoks** [comment]
Thanks! I ended up using a separate docker-compose file instead, as it was roughly as usable as using service-profiles, to get the job done. But service profiles definitely has potential, so really great to be able to use them with docker lock in the future =)
