### ISSUE TITLE
docker-lock-bot no longer available?

### ISSUE THREAD

**Issue by lcarva** [safe-waters/docker-lock#108]
The [docker-lock-bot](https://github.com/marketplace/docker-lock-bot) appears to no longer work. To finalize the installation it redirects to https://github.com/safe-waters/docker-lock-bot which doesn't appear to exist.

(Apologies if this is not the right place to report this issue)

**Comment by michaelperel** [comment]
I removed docker-lock-bot because it had very few users whereas the vast, vast majority of users used docker-lock in ci/cd pipelines and as git hooks. I figured it didn’t make sense to keep paying for the server.

I have tried to remove the app from the marketplace to avoid confusion, but unfortunately github returns a 500 status error and has done so for months.

My apologies for that, and I hope you are able to find it useful in its current form as a cli tool.
