### ISSUE TITLE
errors when parsing docker-compose files with service-definitions with no image stanza

### ISSUE THREAD

**Issue by andoks** [safe-waters/docker-lock#97]
Currently `docker-lock generate` errors out when parsing docker-compose files which contains service-definitions with no image stanza.

I have "composition" compose-files, where we pass multiple compose files to docker-compose (e.g docker-compose --file base-system.docker-compose.yml --file host-specific-options.docker-compose.yml). The "host-specific-options.docker-compose.yml" file in this example may contain only the volumes and port bindings for all the service entries defined in "base-system.docker-compose.yml". Do note that the "addon" docker-compose.yml files may contain image stanzas for certain services (or additional services altogether).

Is it possible to have docker-lock not error out on service-definitions that does not contain an image stanza (and perhaps log or error out if the image stanza is present, but not a valid image)?

**Comment by michaelperel** [comment]
@andoks Could you try running with the Open PR? It should address almost all cases that I can think of except the scenario where `context` and `dockerfile` are split between files, as in that case the file with `context` means "Dockerfile" in the `context` directory and `dockerfile` by itself has no meaning. Since the files are evaluated separately, the file with `dockerfile` would not do anything.

I feel like this is a niche case, or at least a pattern I have never seen followed, so I don't think it should cause any problems.

Here is an example of where it would fail.

`base.yml`
```
version: '3.0'

services:
  web:
    build:
      context: .
```

`host.yml`

```
version: '3.0'

services:
  web:
    build:
      dockerfile: 'Dockerfile1'
```

`Dockerfile1`

```
FROM golang
```

```
docker lock generate --composefiles=base.yml,host.yml
```

This case could be solved by having some kind of flag for `docker-lock` to evaluate the composition of files, but at that point, it may make sense for an individual to just run

```
docker-compose --file base.yml --file host.yml config
```

and run the output through `docker-lock`.

One last thing to note:

Because of the way the docker parser works in the golang cli, you will need each component to have the form
```
version: 'some number'

services:
  ...
```

Some of the docker-compose examples do not include that in each file and instead just specify the services as:

```
web:
  image:
```

Without the `version` block, this defaults to version 1.0, which you wouldn't want, and without the `services` block the docker golang parser chokes.

**Comment by andoks** [comment]
@michaelperel tested the PR on our repo (only on the composefiles in question), and it did not complain about missing name anymore. I might have expected the compose-file to show up in docker-lock.json with empty list of images, which it did not, but not a real issue I think (maybe just a desire stemming from the need right now to verify that the file was analyzed at all).

Regarding the context/dockerfile corner-case you describe, I could imagine uses for it, but we do not have that pattern anywhere in our codebase at least.

Regarding the shortened way of specifying overlay-files (no version stanza, no top-level services stanza), that is a no problem for us, since we specify it in working way anyhow, and it is a trivial thing to change. The only issue with it would be if it is hard to diagnose that this is actually the issue when docker-lock fails, if docker-lock does not print out a useful message (I have not checked if this is the case or not since it is not a use-case we have).

**Comment by andoks** [comment]
BTW, do you get notifications / @'s from [discussions](https://github.com/safe-waters/docker-lock/discussions)? I think I found something that [looks like a bug in --dockerfiles](https://github.com/safe-waters/docker-lock/discussions/92), but I made a discussion topic out of it instead of an issue. Do you prefer uses creating issues instead of discussions perhaps? I see it is possible to [disable the discussion tab](https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository) in that case.

**Comment by michaelperel** [comment]
@andoks Glad it works! Let me know if you would handle that corner case any differently (currently the file with `context` would get evaluated, but the file with `dockerfile` wouldn't (perhaps a warning would suffice?)).

For the shortened stanza, it tells you that keys outside of service are not allowed at the root, and if version is not specified, that version: 1.0 is not allowed.

Interestingly, if you use `docker-compose config` on

```
web:
  image: busybox
```
you will see that the file will default to version 1, which I don't think most people want.

Regarding the discussions, I wasn't getting notifications, but will give it a look!
